### ISSUE TITLE
Crash in Fight

### ISSUE THREAD

**Issue by Xaikii** [IsakViste/RealisticArmorTiers#10]
https://pastebin.com/nJgm1rhw

In Fight
I do not know what was happening there
I didn't even have a Full Armor Set
At this Point I would also recommend that the Armor Sets should be only applied when wearing a Full Set of it and not already when a single piece is equipped

**Comment by Pocketstealer** [comment]
Can you please show the json as well?

It doesn't matter if you have a fullset because the server checks for your items so it doesn't need to check if you have a full set all the time.

I can't reproduce... Probably a potionId is non existent?

With a json i could see what the problem is.

**Comment by Xaikii** [comment]
It's the default generated json, I didn't touch it at all yet.

**Comment by Pocketstealer** [comment]
We tested on 2 separate ocassions. Can you please give more info?

How are you trying the mod, if you have any other mod, the minecraft version.

The error i see is an old commit where it gave that error to other forge versions but it's now fixed.

And what version of our mod you use.

**Comment by Pocketstealer** [comment]
Closed as it cannot be reproduced
