### ISSUE TITLE
[Suggestion] [1.12] Tie hunger to weight

### ISSUE THREAD

**Issue by BitBork** [IsakViste/RealisticArmorTiers#11]
Hi there, had an idea that might increase immersiveness of this mod even further, being to tie the hunger mechanic to the weight of armour sets.
Eg. iron armour will slow the player down as well as deplete hunger faster when worn.

**Comment by IsakViste** [comment]
Hey, sorry for late reply
I will look into this, I stopped the development of this mod some time ago, but I will see what I can do!

**Comment by IsakViste** [comment]
Closing this as it will not be implemented, here is an alternative solution to achieve this:
- Create a set/sets with the hunger effect
