### ISSUE TITLE
Armor sets with less than 4 items do not work

### ISSUE THREAD

**Issue by Mike-T4** [IsakViste/RealisticArmorTiers#2]
I am attempting to add a set effect for an armor set that only has 3 items, however, it would appear that this currently does not work.

┆Attachments: <a href="https:&#x2F;&#x2F;github.com&#x2F;IsakViste&#x2F;RealisticArmorTiers&#x2F;releases&#x2F;tag&#x2F;v1.0.2-1.10.2">v1.0.2</a>

**Comment by IsakViste** [comment]
I have found the problem and will fix it asap!
I will push version 1.0.2 tomorrow morning (Central Europe time) with a fix to this issue.

**Comment by IsakViste** [comment]
[v1.0.2](https://github.com/IsakViste/RealisticArmorTiers/releases/tag/v1.0.2-1.10.2)
