### ISSUE TITLE
Make it possible to use pools for armor pieces

### ISSUE THREAD

**Issue by Arakhor** [IsakViste/RealisticArmorTiers#3]
Make it so tiers are composed of different slots, which have each different items, so that a set, can use a tier slot for it's pieces, instead of a specific item.

- - -
So for example, create a pool "any metal chestplate" with Iron and Golden chestplates, for later use in armor sets.

Also it would help if modID could be specified per item, rather than per set.

**Comment by IsakViste** [comment]
The modID for a specific item could be done, I will try to work on that!
But for the any metal chestplate, I'm not sure I understand what you mean, could you elaborate?

**Comment by Arakhor** [comment]
I figured my explanation might be unclear :p sorry about that.
So let's say I want to configure the mod, so that anytime a player has a full metal armor on, they get resistance 2 buff. Unless I'm missing something, currently it is only possible to configure armor sets for specific items, for example, full golden armor, so if a player switches their helmet to an iron one, the buff gets lost. That could be *fixed* by creating "any metal helmet" pool, with both iron and golden helmets in it, and using that in the armor set instead.

Or maybe I want to make any helmet give "blindness" effect, then I could create a pool with every helmet in the game, and then create armor set giving blindness effect with "any helmet" instead of a specific item.

Hopefully that explains my idea a little better, 
Thank you for your time.

**Comment by IsakViste** [comment]
Okay so to this idea, there's 2 different things right?

1. Full "tier" set, where if you have 4 items from a specific tier, you get set effect?
Example: both minecraft iron and diamond armor are part of plate tier, so you make a set "full metal" where wearing 2 iron and 2 diamond pieces will give you the effects/buffs

2. Specifying in a certain tiers that all the helmets part of this tier gives a specific effect/buff?
Example: both iron helmet and diamond helmet are part of plate tier, so you could say that wearing plate helmet, gives you a specific effect/buff

The 2 ideas are very similar, but act differently, hence why I split your idea in 2 parts ^^
If this is what you meant, than I could probably get the 1st idea to be done prety fast, the 2nd one might take a bit more time, but I'll start working on it asap 👍
If I got it wrong, do correct me!

**Comment by Arakhor** [comment]
Yeah, you got it :D Really I see a great number of uses for your mod, it just needs some more customization freedom. I know I'll be using it extensively should you implement these features. 
Thank you for your time.
