### ISSUE TITLE
[Suggestion][1.12.2] Use potion strings rather than effect ID numbers for configs

### ISSUE THREAD

**Issue by Luke616** [IsakViste/RealisticArmorTiers#9]
Title, using a potion ID string (ex: minecraft:weakness or potioncore:diamond_skin) rather than specifying an effect id (ex: effect: 18) is less cumbersome and more compatible way of configuring potion effects. Not 100% but I'm pretty sure that most mods are automatically assigned IDs for their potions, so adding/removing mods or transferring config files between modpacks may break potion effects. Using this method would also make it easier for packdevs to configure effects, as potion strings are easier to look up than automatically assigned potion IDs.

Thanks for your consideration and for the great mod,
Luke616

**Comment by Pocketstealer** [comment]
Do you have any links with all these effects? minecraft:weakness etc?

Potion requires a resourceLocation so to help others find it, can you provide where do you know about these strings?

Thank you,
Pocket.

**Comment by Giskard13** [comment]
Easiest way for a user to find the potion ID strings would be to use the /effect command in game. They could list all of the effects added through both vanilla and their chosen mods.

I'm really not sure if that helps with the issue or not, but I hope it does. 

Thanks,
Giskard13
